# Generated by Django 5.2 on 2025-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_muscle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Untitled Workout', max_length=100),
        ),
    ]
