# Generated by Django 5.2 on 2025-07-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('powerlifting', 'Powerlifting'), ('strength', 'Strength'), ('stretching', 'Stretching'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting'), ('strongman', 'Strongman'), ('plyometrics', 'Plyometrics')], default='strength', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, choices=[('medicine ball', 'Medicine Ball'), ('dumbbell', 'Dumbbell'), ('body only', 'Body Only'), ('bands', 'Bands'), ('kettlebells', 'Kettlebells'), ('foam roll', 'Foam Roll'), ('cable', 'Cable'), ('machine', 'Machine'), ('barbell', 'Barbell'), ('exercise ball', 'Exercise Ball'), ('e-z curl bar', 'EZ Curl Bar'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(blank=True, choices=[('static', 'Static'), ('pull', 'Pull'), ('push', 'Push')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, choices=[('isolation', 'Isolation'), ('compound', 'Compound')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primaryMuscles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondaryMuscles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
    ]
