# Generated by Django 5.2 on 2025-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_populate_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='total_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
